### ISSUE TITLE
Last BG Date/Time stamp

### ISSUE THREAD

**Issue by gregwaehner** [rnpenguin/cgm-remote-monitor#29]
Hi - First off, I just got my Azure website up and running with CGM-Remote-Monitor -- it's awesome. I don't have experience yet in JSON and node.js coding, but from my initial look, I'm wondering if the client.js could be enhanced to show the last BG time/date stamp? From the MongoDB collection, I'm talking about the fourth element of the array (dateString). If that was shown on the screen after mg/dL - such as 187 mg/DL (as of #dateString) then a consumer would know if the browser hasn't updated, if the phone battery died and CGM data isn't getting transmitted, etc.

But if there's another way to do this already that I've missed, please let me know. Again, I think this is wonderful and can't thank all the contributors enough. Hopefully I'll be able to ramp up quickly and help contribute.
- Greg
  [github: gregwaehner / em: greg@waehner.com]

**Comment by rnpenguin** [comment]
It is possible.  In client.js, the socket.on("sgv") event is passed from the server every minute with an array of data.  The first element in that array is an array of the actual data from the CGM, thus the last element in that array has the last SG from the CGM. I know a couple people have implemented this on their own, but not sure exactly who to point you to so that you could do a copy/paste.  If the CGM data has become stale, then the server adds extra prediction points (blue dots) when sending to the client.  It has never really be done because if the blue points pass the left side of the "now" line when in the current time view, then it is clear that the data is stale.  I will leave this open as an enhancement to implement.

**Comment by rnpenguin** [comment]
closing, currently in community maintained fork at https://github.com/nightscout/cgm-remote-monitor.
